import 'package:flutter/material.dart';

// Catppuccin Latte — https://catppuccin.com/palette
final ThemeData catppuccinLightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFF8839EF),
  colorScheme: const ColorScheme.light(
    primary: Color(0xFF8839EF),
    onPrimary: Color(0xFFEFF1F5),
    primaryContainer: Color(0xFFCCD0DA),
    onPrimaryContainer: Color(0xFF4C4F69),
    secondary: Color(0xFF1E66F5),
    onSecondary: Color(0xFFEFF1F5),
    secondaryContainer: Color(0xFFBCC0CC),
    onSecondaryContainer: Color(0xFF4C4F69),
    tertiary: Color(0xFF179299),
    onTertiary: Color(0xFFEFF1F5),
    tertiaryContainer: Color(0xFFCCD0DA),
    onTertiaryContainer: Color(0xFF4C4F69),
    error: Color(0xFFD20F39),
    onError: Color(0xFFEFF1F5),
    errorContainer: Color(0xFFCCD0DA),
    onErrorContainer: Color(0xFF4C4F69),
    surface: Color(0xFFEFF1F5),
    onSurface: Color(0xFF4C4F69),
    surfaceContainerHighest: Color(0xFFCCD0DA),
    onSurfaceVariant: Color(0xFF6C6F85),
    outline: Color(0xFF9CA0B0),
    inverseSurface: Color(0xFF4C4F69),
    inversePrimary: Color(0xFFCBA6F7),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF8839EF),
    outlineVariant: Color(0xFFBCC0CC),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFFEFF1F5),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF8839EF),
    iconTheme: IconThemeData(color: Color(0xFFEFF1F5)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF4C4F69),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFF4C4F69)),
  ),
  fontFamily: 'Poppins',
);

// Catppuccin Mocha — https://catppuccin.com/palette
final ThemeData catppuccinDarkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFFCBA6F7),
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFFCBA6F7),
    onPrimary: Color(0xFF1E1E2E),
    primaryContainer: Color(0xFF45475A),
    onPrimaryContainer: Color(0xFFCDD6F4),
    secondary: Color(0xFF89B4FA),
    onSecondary: Color(0xFF1E1E2E),
    secondaryContainer: Color(0xFF313244),
    onSecondaryContainer: Color(0xFFCDD6F4),
    tertiary: Color(0xFF94E2D5),
    onTertiary: Color(0xFF1E1E2E),
    tertiaryContainer: Color(0xFF313244),
    onTertiaryContainer: Color(0xFFCDD6F4),
    error: Color(0xFFF38BA8),
    onError: Color(0xFF1E1E2E),
    errorContainer: Color(0xFF45475A),
    onErrorContainer: Color(0xFFCDD6F4),
    surface: Color(0xFF1E1E2E),
    onSurface: Color(0xFFCDD6F4),
    surfaceContainerHighest: Color(0xFF313244),
    onSurfaceVariant: Color(0xFFA6ADC8),
    outline: Color(0xFF6C7086),
    inverseSurface: Color(0xFFCDD6F4),
    inversePrimary: Color(0xFF8839EF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFCBA6F7),
    outlineVariant: Color(0xFF45475A),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFF1E1E2E),
  appBarTheme: const AppBarTheme(
    color: Color(0xFFCBA6F7),
    iconTheme: IconThemeData(color: Color(0xFF1E1E2E)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF1E1E2E),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFFCDD6F4)),
  ),
  fontFamily: 'Poppins',
);
