import 'package:flutter/material.dart';

// Dracula-inspired light complement (no official light variant exists)
final ThemeData draculaLightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFF7C4FE0),
  colorScheme: const ColorScheme.light(
    primary: Color(0xFF7C4FE0),
    onPrimary: Color(0xFFF7F7FB),
    primaryContainer: Color(0xFFE6E0FA),
    onPrimaryContainer: Color(0xFF282A36),
    secondary: Color(0xFFD1399C),
    onSecondary: Color(0xFFF7F7FB),
    secondaryContainer: Color(0xFFFBE0F0),
    onSecondaryContainer: Color(0xFF282A36),
    tertiary: Color(0xFF0E8FA8),
    onTertiary: Color(0xFFF7F7FB),
    tertiaryContainer: Color(0xFFDCF4F8),
    onTertiaryContainer: Color(0xFF282A36),
    error: Color(0xFFD1393A),
    onError: Color(0xFFF7F7FB),
    errorContainer: Color(0xFFFBE2E1),
    onErrorContainer: Color(0xFF282A36),
    surface: Color(0xFFF7F7FB),
    onSurface: Color(0xFF282A36),
    surfaceContainerHighest: Color(0xFFE9E9F2),
    onSurfaceVariant: Color(0xFF5C5E70),
    outline: Color(0xFF8A8CA0),
    inverseSurface: Color(0xFF282A36),
    inversePrimary: Color(0xFFBD93F9),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF7C4FE0),
    outlineVariant: Color(0xFFDADAE6),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFFF7F7FB),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF7C4FE0),
    iconTheme: IconThemeData(color: Color(0xFFF7F7FB)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF282A36),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFF282A36)),
  ),
  fontFamily: 'Poppins',
);

// Dracula — https://draculatheme.com/contribute
final ThemeData draculaDarkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFFBD93F9),
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFFBD93F9),
    onPrimary: Color(0xFF282A36),
    primaryContainer: Color(0xFF44475A),
    onPrimaryContainer: Color(0xFFF8F8F2),
    secondary: Color(0xFFFF79C6),
    onSecondary: Color(0xFF282A36),
    secondaryContainer: Color(0xFF44475A),
    onSecondaryContainer: Color(0xFFF8F8F2),
    tertiary: Color(0xFF8BE9FD),
    onTertiary: Color(0xFF282A36),
    tertiaryContainer: Color(0xFF44475A),
    onTertiaryContainer: Color(0xFFF8F8F2),
    error: Color(0xFFFF5555),
    onError: Color(0xFF282A36),
    errorContainer: Color(0xFF44475A),
    onErrorContainer: Color(0xFFF8F8F2),
    surface: Color(0xFF282A36),
    onSurface: Color(0xFFF8F8F2),
    surfaceContainerHighest: Color(0xFF44475A),
    onSurfaceVariant: Color(0xFFC0C2E0),
    outline: Color(0xFF6272A4),
    inverseSurface: Color(0xFFF8F8F2),
    inversePrimary: Color(0xFF7C4FE0),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFBD93F9),
    outlineVariant: Color(0xFF44475A),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFF282A36),
  appBarTheme: const AppBarTheme(
    color: Color(0xFFBD93F9),
    iconTheme: IconThemeData(color: Color(0xFF282A36)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF282A36),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFFF8F8F2)),
  ),
  fontFamily: 'Poppins',
);
