import 'package:flutter/material.dart';

// Everforest Light (medium) — https://github.com/sainnhe/everforest
final ThemeData everforestLightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFF8DA101),
  colorScheme: const ColorScheme.light(
    primary: Color(0xFF8DA101),
    onPrimary: Color(0xFFFDF6E3),
    primaryContainer: Color(0xFFE6E1CB),
    onPrimaryContainer: Color(0xFF5C6A72),
    secondary: Color(0xFF3A94C5),
    onSecondary: Color(0xFFFDF6E3),
    secondaryContainer: Color(0xFFE6E1CB),
    onSecondaryContainer: Color(0xFF5C6A72),
    tertiary: Color(0xFFDF69BA),
    onTertiary: Color(0xFFFDF6E3),
    tertiaryContainer: Color(0xFFE6E1CB),
    onTertiaryContainer: Color(0xFF5C6A72),
    error: Color(0xFFF85552),
    onError: Color(0xFFFDF6E3),
    errorContainer: Color(0xFFE6E1CB),
    onErrorContainer: Color(0xFF5C6A72),
    surface: Color(0xFFFDF6E3),
    onSurface: Color(0xFF5C6A72),
    surfaceContainerHighest: Color(0xFFE6E1CB),
    onSurfaceVariant: Color(0xFF7D8A79),
    outline: Color(0xFFA6B0A0),
    inverseSurface: Color(0xFF5C6A72),
    inversePrimary: Color(0xFFA7C080),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF8DA101),
    outlineVariant: Color(0xFFE6E1CB),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFFFDF6E3),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF8DA101),
    iconTheme: IconThemeData(color: Color(0xFFFDF6E3)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF5C6A72),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFF5C6A72)),
  ),
  fontFamily: 'Poppins',
);

// Everforest Dark (medium) — https://github.com/sainnhe/everforest
final ThemeData everforestDarkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFFA7C080),
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFFA7C080),
    onPrimary: Color(0xFF2D353B),
    primaryContainer: Color(0xFF3D484D),
    onPrimaryContainer: Color(0xFFD3C6AA),
    secondary: Color(0xFF7FBBB3),
    onSecondary: Color(0xFF2D353B),
    secondaryContainer: Color(0xFF343F44),
    onSecondaryContainer: Color(0xFFD3C6AA),
    tertiary: Color(0xFFD699B6),
    onTertiary: Color(0xFF2D353B),
    tertiaryContainer: Color(0xFF343F44),
    onTertiaryContainer: Color(0xFFD3C6AA),
    error: Color(0xFFE67E80),
    onError: Color(0xFF2D353B),
    errorContainer: Color(0xFF3D484D),
    onErrorContainer: Color(0xFFD3C6AA),
    surface: Color(0xFF2D353B),
    onSurface: Color(0xFFD3C6AA),
    surfaceContainerHighest: Color(0xFF343F44),
    onSurfaceVariant: Color(0xFF9DA9A0),
    outline: Color(0xFF7A8478),
    inverseSurface: Color(0xFFD3C6AA),
    inversePrimary: Color(0xFF8DA101),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFA7C080),
    outlineVariant: Color(0xFF475258),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFF2D353B),
  appBarTheme: const AppBarTheme(
    color: Color(0xFFA7C080),
    iconTheme: IconThemeData(color: Color(0xFF2D353B)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF2D353B),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFFD3C6AA)),
  ),
  fontFamily: 'Poppins',
);
