import 'package:flutter/material.dart';

// GitHub Light — https://github.com/primer/github-vscode-theme
final ThemeData githubLightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFF0969DA),
  colorScheme: const ColorScheme.light(
    primary: Color(0xFF0969DA),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFDDF4FF),
    onPrimaryContainer: Color(0xFF1F2328),
    secondary: Color(0xFF8250DF),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFEEE1FB),
    onSecondaryContainer: Color(0xFF1F2328),
    tertiary: Color(0xFF1A7F37),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFDAFBE1),
    onTertiaryContainer: Color(0xFF1F2328),
    error: Color(0xFFCF222E),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFEBE9),
    onErrorContainer: Color(0xFF1F2328),
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF1F2328),
    surfaceContainerHighest: Color(0xFFEAEEF2),
    onSurfaceVariant: Color(0xFF59636E),
    outline: Color(0xFFD0D7DE),
    inverseSurface: Color(0xFF1F2328),
    inversePrimary: Color(0xFF58A6FF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF0969DA),
    outlineVariant: Color(0xFFEAEEF2),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFFFFFFFF),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF0969DA),
    iconTheme: IconThemeData(color: Color(0xFFFFFFFF)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF1F2328),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFF1F2328)),
  ),
  fontFamily: 'Poppins',
);

// GitHub Dark — https://github.com/primer/github-vscode-theme
final ThemeData githubDarkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFF58A6FF),
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFF58A6FF),
    onPrimary: Color(0xFF0D1117),
    primaryContainer: Color(0xFF30363D),
    onPrimaryContainer: Color(0xFFC9D1D9),
    secondary: Color(0xFFBC8CFF),
    onSecondary: Color(0xFF0D1117),
    secondaryContainer: Color(0xFF30363D),
    onSecondaryContainer: Color(0xFFC9D1D9),
    tertiary: Color(0xFF3FB950),
    onTertiary: Color(0xFF0D1117),
    tertiaryContainer: Color(0xFF30363D),
    onTertiaryContainer: Color(0xFFC9D1D9),
    error: Color(0xFFF85149),
    onError: Color(0xFF0D1117),
    errorContainer: Color(0xFF30363D),
    onErrorContainer: Color(0xFFC9D1D9),
    surface: Color(0xFF0D1117),
    onSurface: Color(0xFFC9D1D9),
    surfaceContainerHighest: Color(0xFF161B22),
    onSurfaceVariant: Color(0xFF8B949E),
    outline: Color(0xFF30363D),
    inverseSurface: Color(0xFFC9D1D9),
    inversePrimary: Color(0xFF0969DA),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF58A6FF),
    outlineVariant: Color(0xFF21262D),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFF0D1117),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF58A6FF),
    iconTheme: IconThemeData(color: Color(0xFF0D1117)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF0D1117),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFFC9D1D9)),
  ),
  fontFamily: 'Poppins',
);
