import 'package:flutter/material.dart';

// Gruvbox Light (hard) — https://github.com/morhetz/gruvbox
final ThemeData gruvboxLightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFFD65D0E),
  colorScheme: const ColorScheme.light(
    primary: Color(0xFFD65D0E),
    onPrimary: Color(0xFFFBF1C7),
    primaryContainer: Color(0xFFEBDBB2),
    onPrimaryContainer: Color(0xFF3C3836),
    secondary: Color(0xFF689D6A),
    onSecondary: Color(0xFFFBF1C7),
    secondaryContainer: Color(0xFFD5C4A1),
    onSecondaryContainer: Color(0xFF3C3836),
    tertiary: Color(0xFF458588),
    onTertiary: Color(0xFFFBF1C7),
    tertiaryContainer: Color(0xFFD5C4A1),
    onTertiaryContainer: Color(0xFF3C3836),
    error: Color(0xFFCC241D),
    onError: Color(0xFFFBF1C7),
    errorContainer: Color(0xFFEBDBB2),
    onErrorContainer: Color(0xFF3C3836),
    surface: Color(0xFFFBF1C7),
    onSurface: Color(0xFF3C3836),
    surfaceContainerHighest: Color(0xFFEBDBB2),
    onSurfaceVariant: Color(0xFF7C6F64),
    outline: Color(0xFFA89984),
    inverseSurface: Color(0xFF3C3836),
    inversePrimary: Color(0xFFFE8019),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFD65D0E),
    outlineVariant: Color(0xFFD5C4A1),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFFFBF1C7),
  appBarTheme: const AppBarTheme(
    color: Color(0xFFD65D0E),
    iconTheme: IconThemeData(color: Color(0xFFFBF1C7)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF3C3836),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFF3C3836)),
  ),
  fontFamily: 'Poppins',
);

// Gruvbox Dark (hard) — https://github.com/morhetz/gruvbox
final ThemeData gruvboxDarkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFFFE8019),
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFFFE8019),
    onPrimary: Color(0xFF282828),
    primaryContainer: Color(0xFFD65D0E),
    onPrimaryContainer: Color(0xFFFBF1C7),
    secondary: Color(0xFF8EC07C),
    onSecondary: Color(0xFF282828),
    secondaryContainer: Color(0xFF504945),
    onSecondaryContainer: Color(0xFFEBDBB2),
    tertiary: Color(0xFF83A598),
    onTertiary: Color(0xFF282828),
    tertiaryContainer: Color(0xFF504945),
    onTertiaryContainer: Color(0xFFEBDBB2),
    error: Color(0xFFFB4934),
    onError: Color(0xFF282828),
    errorContainer: Color(0xFF504945),
    onErrorContainer: Color(0xFFEBDBB2),
    surface: Color(0xFF282828),
    onSurface: Color(0xFFEBDBB2),
    surfaceContainerHighest: Color(0xFF3C3836),
    onSurfaceVariant: Color(0xFFA89984),
    outline: Color(0xFF7C6F64),
    inverseSurface: Color(0xFFEBDBB2),
    inversePrimary: Color(0xFFD65D0E),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFFE8019),
    outlineVariant: Color(0xFF504945),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFF282828),
  appBarTheme: const AppBarTheme(
    color: Color(0xFFFE8019),
    iconTheme: IconThemeData(color: Color(0xFF282828)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF282828),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFFEBDBB2)),
  ),
  fontFamily: 'Poppins',
);
