import 'package:flutter/material.dart';

// Kanagawa Lotus — https://github.com/rebelot/kanagawa.nvim
final ThemeData kanagawaLightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFF4D699B),
  colorScheme: const ColorScheme.light(
    primary: Color(0xFF4D699B),
    onPrimary: Color(0xFFF2ECBC),
    primaryContainer: Color(0xFFDCD5A0),
    onPrimaryContainer: Color(0xFF545464),
    secondary: Color(0xFF624C83),
    onSecondary: Color(0xFFF2ECBC),
    secondaryContainer: Color(0xFFDCD5A0),
    onSecondaryContainer: Color(0xFF545464),
    tertiary: Color(0xFF6F894E),
    onTertiary: Color(0xFFF2ECBC),
    tertiaryContainer: Color(0xFFDCD5A0),
    onTertiaryContainer: Color(0xFF545464),
    error: Color(0xFFC84053),
    onError: Color(0xFFF2ECBC),
    errorContainer: Color(0xFFDCD5A0),
    onErrorContainer: Color(0xFF545464),
    surface: Color(0xFFF2ECBC),
    onSurface: Color(0xFF545464),
    surfaceContainerHighest: Color(0xFFDCD5A0),
    onSurfaceVariant: Color(0xFF716E61),
    outline: Color(0xFF9A9583),
    inverseSurface: Color(0xFF545464),
    inversePrimary: Color(0xFF7E9CD8),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF4D699B),
    outlineVariant: Color(0xFFDCD5A0),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFFF2ECBC),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF4D699B),
    iconTheme: IconThemeData(color: Color(0xFFF2ECBC)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF545464),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFF545464)),
  ),
  fontFamily: 'Poppins',
);

// Kanagawa Wave — https://github.com/rebelot/kanagawa.nvim
final ThemeData kanagawaDarkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFF7E9CD8),
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFF7E9CD8),
    onPrimary: Color(0xFF1F1F28),
    primaryContainer: Color(0xFF2A2A37),
    onPrimaryContainer: Color(0xFFDCD7BA),
    secondary: Color(0xFF957FB8),
    onSecondary: Color(0xFF1F1F28),
    secondaryContainer: Color(0xFF2A2A37),
    onSecondaryContainer: Color(0xFFDCD7BA),
    tertiary: Color(0xFF98BB6C),
    onTertiary: Color(0xFF1F1F28),
    tertiaryContainer: Color(0xFF2A2A37),
    onTertiaryContainer: Color(0xFFDCD7BA),
    error: Color(0xFFC34043),
    onError: Color(0xFF1F1F28),
    errorContainer: Color(0xFF2A2A37),
    onErrorContainer: Color(0xFFDCD7BA),
    surface: Color(0xFF1F1F28),
    onSurface: Color(0xFFDCD7BA),
    surfaceContainerHighest: Color(0xFF2A2A37),
    onSurfaceVariant: Color(0xFFC8C093),
    outline: Color(0xFF727169),
    inverseSurface: Color(0xFFDCD7BA),
    inversePrimary: Color(0xFF4D699B),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF7E9CD8),
    outlineVariant: Color(0xFF363646),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFF1F1F28),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF7E9CD8),
    iconTheme: IconThemeData(color: Color(0xFF1F1F28)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF1F1F28),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFFDCD7BA)),
  ),
  fontFamily: 'Poppins',
);
