import 'package:flutter/material.dart';

// Monokai-inspired light complement (no official light variant exists)
final ThemeData monokaiLightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFF7C3FE0),
  colorScheme: const ColorScheme.light(
    primary: Color(0xFF7C3FE0),
    onPrimary: Color(0xFFFAFAF8),
    primaryContainer: Color(0xFFECE3FB),
    onPrimaryContainer: Color(0xFF272822),
    secondary: Color(0xFFD6265F),
    onSecondary: Color(0xFFFAFAF8),
    secondaryContainer: Color(0xFFFBE0E8),
    onSecondaryContainer: Color(0xFF272822),
    tertiary: Color(0xFF1F93AB),
    onTertiary: Color(0xFFFAFAF8),
    tertiaryContainer: Color(0xFFDCF4F8),
    onTertiaryContainer: Color(0xFF272822),
    error: Color(0xFFD6265F),
    onError: Color(0xFFFAFAF8),
    errorContainer: Color(0xFFFBE0E8),
    onErrorContainer: Color(0xFF272822),
    surface: Color(0xFFFAFAF8),
    onSurface: Color(0xFF272822),
    surfaceContainerHighest: Color(0xFFECE9E2),
    onSurfaceVariant: Color(0xFF5A5950),
    outline: Color(0xFF8C8A7D),
    inverseSurface: Color(0xFF272822),
    inversePrimary: Color(0xFFAE81FF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF7C3FE0),
    outlineVariant: Color(0xFFDEDAD0),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFFFAFAF8),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF7C3FE0),
    iconTheme: IconThemeData(color: Color(0xFFFAFAF8)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF272822),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFF272822)),
  ),
  fontFamily: 'Poppins',
);

// Monokai Classic — https://monokai.pro/
final ThemeData monokaiDarkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFFAE81FF),
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFFAE81FF),
    onPrimary: Color(0xFF272822),
    primaryContainer: Color(0xFF3E3D32),
    onPrimaryContainer: Color(0xFFF8F8F2),
    secondary: Color(0xFFF92672),
    onSecondary: Color(0xFF272822),
    secondaryContainer: Color(0xFF3E3D32),
    onSecondaryContainer: Color(0xFFF8F8F2),
    tertiary: Color(0xFF66D9EF),
    onTertiary: Color(0xFF272822),
    tertiaryContainer: Color(0xFF3E3D32),
    onTertiaryContainer: Color(0xFFF8F8F2),
    error: Color(0xFFF92672),
    onError: Color(0xFF272822),
    errorContainer: Color(0xFF3E3D32),
    onErrorContainer: Color(0xFFF8F8F2),
    surface: Color(0xFF272822),
    onSurface: Color(0xFFF8F8F2),
    surfaceContainerHighest: Color(0xFF3E3D32),
    onSurfaceVariant: Color(0xFFC8C5BC),
    outline: Color(0xFF75715E),
    inverseSurface: Color(0xFFF8F8F2),
    inversePrimary: Color(0xFF7C3FE0),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFAE81FF),
    outlineVariant: Color(0xFF49483E),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFF272822),
  appBarTheme: const AppBarTheme(
    color: Color(0xFFAE81FF),
    iconTheme: IconThemeData(color: Color(0xFF272822)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF272822),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFFF8F8F2)),
  ),
  fontFamily: 'Poppins',
);
