import 'package:flutter/material.dart';

// Nord Light (Snow Storm) — https://www.nordtheme.com/
final ThemeData nordLightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFF5E81AC),
  colorScheme: const ColorScheme.light(
    primary: Color(0xFF5E81AC),
    onPrimary: Color(0xFFECEFF4),
    primaryContainer: Color(0xFFD8DEE9),
    onPrimaryContainer: Color(0xFF2E3440),
    secondary: Color(0xFF81A1C1),
    onSecondary: Color(0xFFECEFF4),
    secondaryContainer: Color(0xFFE5E9F0),
    onSecondaryContainer: Color(0xFF2E3440),
    tertiary: Color(0xFF5B8C8A),
    onTertiary: Color(0xFFECEFF4),
    tertiaryContainer: Color(0xFFE5E9F0),
    onTertiaryContainer: Color(0xFF2E3440),
    error: Color(0xFFBF616A),
    onError: Color(0xFFECEFF4),
    errorContainer: Color(0xFFE5E9F0),
    onErrorContainer: Color(0xFF2E3440),
    surface: Color(0xFFECEFF4),
    onSurface: Color(0xFF2E3440),
    surfaceContainerHighest: Color(0xFFE5E9F0),
    onSurfaceVariant: Color(0xFF4C566A),
    outline: Color(0xFF9AA6B5),
    inverseSurface: Color(0xFF2E3440),
    inversePrimary: Color(0xFF88C0D0),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF5E81AC),
    outlineVariant: Color(0xFFD8DEE9),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFFECEFF4),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF5E81AC),
    iconTheme: IconThemeData(color: Color(0xFFECEFF4)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF2E3440),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFF2E3440)),
  ),
  fontFamily: 'Poppins',
);

// Nord Dark (Polar Night) — https://www.nordtheme.com/
final ThemeData nordDarkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFF88C0D0),
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFF88C0D0),
    onPrimary: Color(0xFF2E3440),
    primaryContainer: Color(0xFF4C566A),
    onPrimaryContainer: Color(0xFFECEFF4),
    secondary: Color(0xFF81A1C1),
    onSecondary: Color(0xFF2E3440),
    secondaryContainer: Color(0xFF3B4252),
    onSecondaryContainer: Color(0xFFECEFF4),
    tertiary: Color(0xFF8FBCBB),
    onTertiary: Color(0xFF2E3440),
    tertiaryContainer: Color(0xFF434C5E),
    onTertiaryContainer: Color(0xFFECEFF4),
    error: Color(0xFFBF616A),
    onError: Color(0xFF2E3440),
    errorContainer: Color(0xFF434C5E),
    onErrorContainer: Color(0xFFECEFF4),
    surface: Color(0xFF2E3440),
    onSurface: Color(0xFFE5E9F0),
    surfaceContainerHighest: Color(0xFF3B4252),
    onSurfaceVariant: Color(0xFFD8DEE9),
    outline: Color(0xFF4C566A),
    inverseSurface: Color(0xFFE5E9F0),
    inversePrimary: Color(0xFF5E81AC),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF88C0D0),
    outlineVariant: Color(0xFF434C5E),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFF2E3440),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF88C0D0),
    iconTheme: IconThemeData(color: Color(0xFF2E3440)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF2E3440),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFFE5E9F0)),
  ),
  fontFamily: 'Poppins',
);
