import 'package:flutter/material.dart';

// Atom One Light
final ThemeData oneDarkLightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFF4078F2),
  colorScheme: const ColorScheme.light(
    primary: Color(0xFF4078F2),
    onPrimary: Color(0xFFFAFAFA),
    primaryContainer: Color(0xFFEAEAEB),
    onPrimaryContainer: Color(0xFF383A42),
    secondary: Color(0xFFA626A4),
    onSecondary: Color(0xFFFAFAFA),
    secondaryContainer: Color(0xFFEAEAEB),
    onSecondaryContainer: Color(0xFF383A42),
    tertiary: Color(0xFF0184BC),
    onTertiary: Color(0xFFFAFAFA),
    tertiaryContainer: Color(0xFFEAEAEB),
    onTertiaryContainer: Color(0xFF383A42),
    error: Color(0xFFE45649),
    onError: Color(0xFFFAFAFA),
    errorContainer: Color(0xFFEAEAEB),
    onErrorContainer: Color(0xFF383A42),
    surface: Color(0xFFFAFAFA),
    onSurface: Color(0xFF383A42),
    surfaceContainerHighest: Color(0xFFEAEAEB),
    onSurfaceVariant: Color(0xFF696C77),
    outline: Color(0xFFA0A1A7),
    inverseSurface: Color(0xFF383A42),
    inversePrimary: Color(0xFF61AFEF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF4078F2),
    outlineVariant: Color(0xFFD3D3D3),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFFFAFAFA),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF4078F2),
    iconTheme: IconThemeData(color: Color(0xFFFAFAFA)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF383A42),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFF383A42)),
  ),
  fontFamily: 'Poppins',
);

// Atom One Dark
final ThemeData oneDarkDarkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFF61AFEF),
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFF61AFEF),
    onPrimary: Color(0xFF282C34),
    primaryContainer: Color(0xFF3A3F4B),
    onPrimaryContainer: Color(0xFFABB2BF),
    secondary: Color(0xFFC678DD),
    onSecondary: Color(0xFF282C34),
    secondaryContainer: Color(0xFF3E4451),
    onSecondaryContainer: Color(0xFFABB2BF),
    tertiary: Color(0xFF56B6C2),
    onTertiary: Color(0xFF282C34),
    tertiaryContainer: Color(0xFF3E4451),
    onTertiaryContainer: Color(0xFFABB2BF),
    error: Color(0xFFE06C75),
    onError: Color(0xFF282C34),
    errorContainer: Color(0xFF3A3F4B),
    onErrorContainer: Color(0xFFABB2BF),
    surface: Color(0xFF282C34),
    onSurface: Color(0xFFABB2BF),
    surfaceContainerHighest: Color(0xFF3E4451),
    onSurfaceVariant: Color(0xFF9DA5B4),
    outline: Color(0xFF5C6370),
    inverseSurface: Color(0xFFABB2BF),
    inversePrimary: Color(0xFF4078F2),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF61AFEF),
    outlineVariant: Color(0xFF3E4451),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFF282C34),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF61AFEF),
    iconTheme: IconThemeData(color: Color(0xFF282C34)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF282C34),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFFABB2BF)),
  ),
  fontFamily: 'Poppins',
);
