import 'package:flutter/material.dart';

// Rosé Pine Dawn — https://rosepinetheme.com/palette/
final ThemeData rosePineLightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFFD7827E),
  colorScheme: const ColorScheme.light(
    primary: Color(0xFFD7827E),
    onPrimary: Color(0xFFFAF4ED),
    primaryContainer: Color(0xFFF2E9E1),
    onPrimaryContainer: Color(0xFF575279),
    secondary: Color(0xFF907AA9),
    onSecondary: Color(0xFFFAF4ED),
    secondaryContainer: Color(0xFFF4EDE8),
    onSecondaryContainer: Color(0xFF575279),
    tertiary: Color(0xFF56949F),
    onTertiary: Color(0xFFFAF4ED),
    tertiaryContainer: Color(0xFFDFDAD9),
    onTertiaryContainer: Color(0xFF286983),
    error: Color(0xFFB4637A),
    onError: Color(0xFFFAF4ED),
    errorContainer: Color(0xFFF2E9E1),
    onErrorContainer: Color(0xFF575279),
    surface: Color(0xFFFAF4ED),
    onSurface: Color(0xFF575279),
    surfaceContainerHighest: Color(0xFFF2E9E1),
    onSurfaceVariant: Color(0xFF797593),
    outline: Color(0xFF9893A5),
    inverseSurface: Color(0xFF575279),
    inversePrimary: Color(0xFFEBBCBA),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFD7827E),
    outlineVariant: Color(0xFFDFDAD9),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFFFAF4ED),
  appBarTheme: const AppBarTheme(
    color: Color(0xFFD7827E),
    iconTheme: IconThemeData(color: Color(0xFFFAF4ED)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF575279),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFF575279)),
  ),
  fontFamily: 'Poppins',
);

// Rosé Pine (main) — https://rosepinetheme.com/palette/
final ThemeData rosePineDarkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFFEBBCBA),
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFFEBBCBA),
    onPrimary: Color(0xFF191724),
    primaryContainer: Color(0xFF403D52),
    onPrimaryContainer: Color(0xFFE0DEF4),
    secondary: Color(0xFFC4A7E7),
    onSecondary: Color(0xFF191724),
    secondaryContainer: Color(0xFF26233A),
    onSecondaryContainer: Color(0xFFE0DEF4),
    tertiary: Color(0xFF9CCFD8),
    onTertiary: Color(0xFF191724),
    tertiaryContainer: Color(0xFF31748F),
    onTertiaryContainer: Color(0xFFE0DEF4),
    error: Color(0xFFEB6F92),
    onError: Color(0xFF191724),
    errorContainer: Color(0xFF403D52),
    onErrorContainer: Color(0xFFE0DEF4),
    surface: Color(0xFF191724),
    onSurface: Color(0xFFE0DEF4),
    surfaceContainerHighest: Color(0xFF26233A),
    onSurfaceVariant: Color(0xFF908CAA),
    outline: Color(0xFF6E6A86),
    inverseSurface: Color(0xFFE0DEF4),
    inversePrimary: Color(0xFFD7827E),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFEBBCBA),
    outlineVariant: Color(0xFF403D52),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFF191724),
  appBarTheme: const AppBarTheme(
    color: Color(0xFFEBBCBA),
    iconTheme: IconThemeData(color: Color(0xFF191724)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF191724),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFFE0DEF4)),
  ),
  fontFamily: 'Poppins',
);
