import 'package:flutter/material.dart';

// Tokyo Night Day — https://github.com/folke/tokyonight.nvim
final ThemeData tokyonightLightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFF34548A),
  colorScheme: const ColorScheme.light(
    primary: Color(0xFF34548A),
    onPrimary: Color(0xFFD5D6DB),
    primaryContainer: Color(0xFFC4C8DA),
    onPrimaryContainer: Color(0xFF343B58),
    secondary: Color(0xFF5A4A78),
    onSecondary: Color(0xFFD5D6DB),
    secondaryContainer: Color(0xFFC4C8DA),
    onSecondaryContainer: Color(0xFF343B58),
    tertiary: Color(0xFF0F4B6E),
    onTertiary: Color(0xFFD5D6DB),
    tertiaryContainer: Color(0xFFC4C8DA),
    onTertiaryContainer: Color(0xFF343B58),
    error: Color(0xFF8C4351),
    onError: Color(0xFFD5D6DB),
    errorContainer: Color(0xFFC4C8DA),
    onErrorContainer: Color(0xFF343B58),
    surface: Color(0xFFD5D6DB),
    onSurface: Color(0xFF343B58),
    surfaceContainerHighest: Color(0xFFC4C8DA),
    onSurfaceVariant: Color(0xFF565A6E),
    outline: Color(0xFF9699A3),
    inverseSurface: Color(0xFF343B58),
    inversePrimary: Color(0xFF7AA2F7),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF34548A),
    outlineVariant: Color(0xFFC4C8DA),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFFD5D6DB),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF34548A),
    iconTheme: IconThemeData(color: Color(0xFFD5D6DB)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF343B58),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFF343B58)),
  ),
  fontFamily: 'Poppins',
);

// Tokyo Night — https://github.com/folke/tokyonight.nvim
final ThemeData tokyonightDarkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFF7AA2F7),
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFF7AA2F7),
    onPrimary: Color(0xFF1A1B26),
    primaryContainer: Color(0xFF292E42),
    onPrimaryContainer: Color(0xFFC0CAF5),
    secondary: Color(0xFFBB9AF7),
    onSecondary: Color(0xFF1A1B26),
    secondaryContainer: Color(0xFF292E42),
    onSecondaryContainer: Color(0xFFC0CAF5),
    tertiary: Color(0xFF7DCFFF),
    onTertiary: Color(0xFF1A1B26),
    tertiaryContainer: Color(0xFF292E42),
    onTertiaryContainer: Color(0xFFC0CAF5),
    error: Color(0xFFF7768E),
    onError: Color(0xFF1A1B26),
    errorContainer: Color(0xFF292E42),
    onErrorContainer: Color(0xFFC0CAF5),
    surface: Color(0xFF1A1B26),
    onSurface: Color(0xFFC0CAF5),
    surfaceContainerHighest: Color(0xFF292E42),
    onSurfaceVariant: Color(0xFFA9B1D6),
    outline: Color(0xFF565F89),
    inverseSurface: Color(0xFFC0CAF5),
    inversePrimary: Color(0xFF34548A),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF7AA2F7),
    outlineVariant: Color(0xFF414868),
    scrim: Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFF1A1B26),
  appBarTheme: const AppBarTheme(
    color: Color(0xFF7AA2F7),
    iconTheme: IconThemeData(color: Color(0xFF1A1B26)),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      color: Color(0xFF1A1B26),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    bodyLarge: TextStyle(color: Color(0xFFC0CAF5)),
  ),
  fontFamily: 'Poppins',
);
