platform :osx, '12.0' 

workspace 'Runner.xcworkspace' 

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Post-install processing
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_macos_build_settings(target) 
      target.build_configurations.each do |config|
        config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '12.0' # Minimum macOS version
      end
    end
  end
end
