name: RELEASE
on:
  push:
    tags: 
      - "v*.*.*"
jobs:
  build_android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: flutter pub get
      - run: flutter build apk
      - run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Dartotsu_Android_${{github.ref_name}}.apk
      - name: Android Apk Release
        uses: softprops/action-gh-release@master
        with:
            files: build/app/outputs/flutter-apk/Dartotsu_Android_${{github.ref_name}}.apk
  build_windows:
    runs-on: windows-latest
    permissions: 
        contents: write
        pull-requests: write
        repository-projects: write
    steps:
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: flutter pub get
      - run: flutter build windows
      - name: Archive App
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: Dartotsu_Windows_${{github.ref_name}}.zip
          directory: build\windows\x64\runner\Release
      - run: ls build\windows\x64\runner\Release
      - name: Release Windows Zip
        uses: softprops/action-gh-release@master
        with:
            files: build/windows/x64/runner/Release/Dartotsu_Windows_${{github.ref_name}}.zip
        
    
  build_linux:
    runs-on: ubuntu-latest
    permissions: 
        contents: write
        pull-requests: write
        repository-projects: write
    steps:
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev webkit2gtk-4.1
      - run: flutter pub get
      - run: flutter build linux
      - name: Archive app
        uses: thedoctor0/zip-release@master
        with:
            type: 'zip'
            filename: Dartotsu_Linux_${{github.ref_name}}.zip
            directory: build/linux/x64/release/bundle
      - name: Release Linux Zip
        uses: softprops/action-gh-release@master
        with:
            files: build/linux/x64/release/bundle/Dartotsu_Linux_${{github.ref_name}}.zip
  build_ios_and_macos:
    runs-on: macos-13
    permissions: 
        contents: write
        pull-requests: write
        repository-projects: write
    steps:
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - name: Release ios App
        uses: softprops/action-gh-release@master
        with:
            files: build/ios/iphoneos/Runner.app
      - run: flutter build macos
      - name: Archive App
        uses: thedoctor0/zip-release@master
        with:
            type: 'zip'
            filename: Dartotsu_MacOS_${{github.ref_name}}.zip
            directory: build/macos/Build/Products/Release
      - name: Release MacOS Zip
        uses: softprops/action-gh-release@master
        with:
            files: build/macos/Build/Products/Release/Dartotsu_MacOS_${{github.ref_name}}.zip
  upload_download_url:
    runs-on: ubuntu-latest
    needs: [build_android,build_windows,build_linux,build_ios_and_macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{secrets.FINE_GRAIN_TOKEN}}" | gh auth login --with-token

      - name: Fetch latest release assets with gh
        id: fetch_assets
        run: |
          gh release view --repo ${{github.repository}} ${{github.ref_name}} --json assets --jq '.assets[].url' > asset_links.txt

      - name: Print fetched List
        run: cat asset_links.txt

      - name: Read, sort, and format links from the file
        id: format_links
        run: |
          # Read links from the file
          LINKS=$(cat asset_links.txt | sort)
          
          # Initialize the message
          MESSAGE="**Dartotsu ${{github.ref_name}} Downloads:**\n\n"
          
          # Loop through each link and format them
          while IFS= read -r LINK; do
            if [[ $LINK == *"Android"* ]]; then
              MESSAGE+="• [Android]($LINK)\n"
            elif [[ $LINK == *"IOS"* ]]; then
              MESSAGE+="• [iOS]($LINK)\n"
            elif [[ $LINK == *"Linux"* ]]; then
              MESSAGE+="• [Linux]($LINK)\n"
            elif [[ $LINK == *"MacOS"* ]]; then
              MESSAGE+="• [macOS]($LINK)\n"
            elif [[ $LINK == *"Windows"* ]]; then
              MESSAGE+="• [Windows]($LINK)\n"
            fi
          done <<< "$LINKS"

          # Save the message to an environment variable
          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MESSAGE: ${{ env.MESSAGE }}
        run: |
          # Send the message to Discord using the webhook
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"$MESSAGE\"}" \
            $DISCORD_WEBHOOK_URL
          
  generate-changelog:
    runs-on: ubuntu-latest
    needs: [build_android,build_windows,build_linux,build_ios_and_macos]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Clear existing CHANGELOG.md
      - name: Clear CHANGELOG.md
        run: |
          echo ""> CHANGELOG.md
          echo "" >> CHANGELOG.md
          
      - name: Get previous tag
        id: get_prev_tag
        run: |
          echo "Getting the previous tag..."
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            PREV_TAG=$(git rev-list --max-parents=0 HEAD)
          fi
          echo "prev_tag=$PREV_TAG" >> $GITHUB_ENV

      - name: Get commit messages between tags
        id: get_commits
        run: |
          COMMITS=$(git log ${{ env.prev_tag }}..HEAD --pretty=format:'%h %s' | tr '\n' '|')
          echo "commits=$COMMITS" >> $GITHUB_ENV

      - name: Categorize commits
        id: categorize
        run: |
          echo "Categorizing commits..."
          FEATURES=""
          BUG_FIXES=""
          REFACTORS=""
          STYLE_CHANGES=""
          PERFORMANCE=""
          CHORES=""
          REPO_URL="https://github.com/${{ github.repository }}"
    
          IFS='|' read -ra COMMIT_LIST <<< "${{ env.commits }}"
          echo "Commit list: ${COMMIT_LIST[@]}"
          for LINE in "${COMMIT_LIST[@]}"; do
          HASH=$(echo "$LINE" | awk '{print $1}')
          MESSAGE=$(echo "$LINE" | cut -d' ' -f2-)
          LINK="[$HASH]($REPO_URL/commit/$HASH)"

          FORMATTED_COMMIT="* $LINK: $MESSAGE"
          echo "Processing commit: $FORMATTED_COMMIT"
          if [[ $MESSAGE == feat* ]]; then
           FEATURES+="$FORMATTED_COMMIT\n"
          elif [[ $MESSAGE == fix* || $MESSAGE == bug* || $MESSAGE == improvement* || $MESSAGE == patch* ]]; then
          BUG_FIXES+="$FORMATTED_COMMIT\n"
          elif [[ $MESSAGE == refactor* ]]; then
          REFACTORS+="$FORMATTED_COMMIT\n"
          elif [[ $MESSAGE == style* ]]; then
          STYLE_CHANGES+="$FORMATTED_COMMIT\n"
          elif [[ $MESSAGE == perf* ]]; then
          PERFORMANCE+="$FORMATTED_COMMIT\n"
          elif [[ $MESSAGE == chore* || $MESSAGE == docs* || $MESSAGE == build* || $MESSAGE == ci* ]]; then
          CHORES+="$FORMATTED_COMMIT\n"
          fi
          done

          # Removed the version tag section
          # echo "### ${GITHUB_REF#refs/tags/}" >> CHANGELOG.md  # No version tag added

          if [ -n "$FEATURES" ]; then
          echo "### 🎉 New Features" >> CHANGELOG.md
          echo -e "$FEATURES" >> CHANGELOG.md
          fi
          if [ -n "$BUG_FIXES" ]; then
          echo "### 🛠️ Bug Fixes & Improvements" >> CHANGELOG.md
          echo -e "$BUG_FIXES" >> CHANGELOG.md
          fi
          if [ -n "$REFACTORS" ]; then
          echo "### 🔧 Refactors" >> CHANGELOG.md
          echo -e "$REFACTORS" >> CHANGELOG.md
          fi
          if [ -n "$STYLE_CHANGES" ]; then
          echo "### 🎨 Style Changes" >> CHANGELOG.md
          echo -e "$STYLE_CHANGES" >> CHANGELOG.md
          fi
          if [ -n "$PERFORMANCE" ]; then
          echo "### 🚀 Performance Improvements" >> CHANGELOG.md
            echo -e "$PERFORMANCE" >> CHANGELOG.md
          fi
          if [ -n "$CHORES" ]; then
            echo "### 🧹 Chores & Documentation" >> CHANGELOG.md
            echo -e "$CHORES" >> CHANGELOG.md
          fi
          
      - name: Commit and push changelog
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update changelog for version ${{ github.ref_name }}"
          git push origin HEAD:main

      - name: Set Tag Variable
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: CHANGELOG.md
          tag: ${{ env.TAG }}
          allowUpdates: true
